### ISSUE TITLE
CardScanActivity vs CardScanFlow warmUp/prepareScan

### ISSUE THREAD

**Issue by francescocervone** [getbouncer/cardscan-android#434]
I have a doubt about the public API.
It looks like `CardScanActivity` and `CardScanFlow` companion objects have pretty much the same public API.
Documentation says we should use `CardScanActivity.warmUp`, but for some reason we always used `CardScanFlow`.
Now that in release [2.1.0008](https://github.com/getbouncer/cardscan-android/releases/tag/2.1.0008) with https://github.com/getbouncer/cardscan-android/pull/426 you removed `CardScanFlow.warmUp`, it makes me think that we should switch to `CardScanActivity`.

What should we use? `CardScanActivity` or `CardScanFlow`?
If the answer is `CardScanActivity`, may I suggest to make `CardScanFlow` internal?

Thanks.

**Comment by awushensky-stripe** [comment]
Hi @francescocervone , sorry for the confusion here. You're correct that CardScanActivity is the public interface, and CardScanFlow is more internal to the application. Unfortunately, I cannot make CardScanFlow `internal` since the CardVerify product extends the functionality of the `CardScanFlow` class in another package. However, I can restrict access to the library, so that's what I'll do.

Thank you for the valuable feedback as always! I'll add that flag in the next release, version 2.1.0008

**Comment by awushensky-stripe** [comment]
https://github.com/getbouncer/cardscan-android/pull/436

**Comment by francescocervone** [comment]
Thanks!
