### ISSUE TITLE
Unable to create an APK key

### ISSUE THREAD

**Issue by ananth10** [getbouncer/cardscan-android#536]
Hi Team,

I have integrated Card Scan Ocr in my android application but I am not able create an API key because that link [Bouncer API console](https://api.getbouncer.com/console) given in README is broken. please check the attached screenshot and let me know the updated bouncer console website link.

Thanks!!
<img width="1546" alt="Screenshot 2022-08-25 at 4 58 34 PM" src="https://user-images.githubusercontent.com/13381242/187201574-0a925746-75ad-4452-b8f7-97ded1190c06.png">

**Comment by awush-stripe** [comment]
Hi @ananth10 , thank you for calling out the broken link, I'll update that portion of the README. This project was replaced by [stripe cardscan](https://github.com/stripe/stripe-android/tree/master/stripecardscan), and the console has been shut down; new API keys can no longer be provisioned. I believe [we spoke briefly](https://github.com/stripe/stripe-android/issues/5430) on the stripe-android repository about CardScan there. That library replaces this one entirely.

**Comment by ananth10** [comment]
@awush-stripe Thanks for your reply! I have integrated this bouncer card scan SDK in android app because this SDK able extracts both card number and expiry date and also able to customise scanner UI screen but the new stripe cardscan  only extracts card number now and that is why i have planned to use this bouncer cardscan SDK now and once your team implemented expiry extract feature in stripe cardscan SDK then I will migrate to stripe cardscan SDK. and our use case is app should extract both card number and expiry from user card. so following 2 issues i am facing in new [stripe cardscan](https://github.com/stripe/stripe-android/tree/master/stripecardscan) SDK

1. Expiry extract feature is not currently available in the [stripe cardscan](https://github.com/stripe/stripe-android/tree/master/stripecardscan)
2. Scanner UI customisation is not currently available in the [stripe cardscan](https://github.com/stripe/stripe-android/tree/master/stripecardscan)

So I am stuck here, I need your help on this.

**Comment by awush-stripe** [comment]
I understand and empathize with your concerns. The bouncer SDK was about 10% accurate on extracting expiry, which is why we removed it from the stripe cardscan until we can improve it to be much more reliable.

UI customization in the legacy bouncer SDK exposed a lot of our internal APIs that drastically limited the improvements we could make without breaking customization.

On the stripe cardscan solution, there is some customization you can do in terms of colors, spacing, fonts, etc. by overriding XML values. I know you were concerned about the "I can't scan this card" button. I've been speaking with our designer about that button and getting it prioritized. While I don't have a date for you yet, it is on our radar and we're thinking about how we can make the verify + scan SDKs have parity.

**Comment by ananth10** [comment]
@awush-stripe Thanks again!! I will try with the [stripe cardscan](https://github.com/stripe/stripe-android/tree/master/stripecardscan) and hoping expiry extraction feature will be added in sdk soon.
